import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { useQuiz } from '../context/QuizContext';
import AIQuizGenerator from '../components/AIQuizGenerator';

const containerVariants = {
  hidden: { opacity: 0 },
  visible: { opacity: 1, transition: { staggerChildren: 0.1 } },
};

const itemVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.4 } },
};

export default function AIQuiz() {
  const navigate = useNavigate();
  const { isDark, startQuiz } = useQuiz();

  const handleQuestionsReady = (questions) => {
    startQuiz(questions);
    navigate('/quiz');
  };

  return (
    <div className={`min-h-screen pt-24 pb-12 px-4 ${isDark ? 'gradient-bg' : 'gradient-bg-light'}`}>
      <motion.div
        variants={containerVariants}
        initial="hidden"
        animate="visible"
        className="max-w-xl mx-auto"
      >
        {/* Header */}
        <motion.div variants={itemVariants} className="text-center mb-10">
          <motion.div
            animate={{ rotate: [0, -10, 10, 0] }}
            transition={{ repeat: Infinity, repeatDelay: 4, duration: 0.8 }}
            className="text-7xl mb-4"
          >
            🤖
          </motion.div>
          <h1 className={`text-5xl font-black mb-2 ${isDark ? 'text-white' : 'text-gray-900'}`}>
            AI <span className="text-gradient">Quiz</span>
          </h1>
          <p className={`text-lg ${isDark ? 'text-gray-300' : 'text-gray-600'}`}>
            Upload your study material and let Claude generate questions for you
          </p>
        </motion.div>

        {/* Main card */}
        <motion.div
          variants={itemVariants}
          className={`rounded-2xl p-6 md:p-8 ${isDark ? 'card-glass' : 'card-glass-light'}`}
        >
          <div className="mb-6">
            <h2 className={`text-lg font-bold mb-1 ${isDark ? 'text-white' : 'text-gray-900'}`}>
              Upload Your Notes
            </h2>
            <p className={`text-sm ${isDark ? 'text-gray-400' : 'text-gray-500'}`}>
              PDF or Word (.docx) · Max 20 MB
            </p>
          </div>

          <AIQuizGenerator onQuestionsReady={handleQuestionsReady} />
        </motion.div>

        {/* Feature chips */}
        <motion.div variants={itemVariants} className="mt-6 grid grid-cols-3 gap-3">
          {[
            { icon: '📚', label: 'Any Subject' },
            { icon: '⚡', label: '10 Questions' },
            { icon: '🎯', label: 'AI Powered' },
          ].map((item) => (
            <div
              key={item.label}
              className={`rounded-xl p-3 text-center ${
                isDark
                  ? 'bg-white/5 border border-white/10'
                  : 'bg-white/60 border border-gray-100'
              }`}
            >
              <div className="text-2xl mb-1">{item.icon}</div>
              <div className={`text-xs font-medium ${isDark ? 'text-gray-400' : 'text-gray-500'}`}>
                {item.label}
              </div>
            </div>
          ))}
        </motion.div>

        {/* Powered-by note */}
        <motion.p
          variants={itemVariants}
          className={`text-center text-sm mt-6 ${isDark ? 'text-gray-500' : 'text-gray-400'}`}
        >
          Questions generated by{' '}
          <span className="text-violet-400 font-medium">Claude (via OpenRouter)</span>
        </motion.p>
      </motion.div>
    </div>
  );
}
